name: Deploy ChatBot with Bash Scripts

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up SSH Access
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.FRONTEND_IP }} >> ~/.ssh/known_hosts
        ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.BACKEND_IP }} >> ~/.ssh/known_hosts

    - name: Test SSH Connection (Frontend)
      run: ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.FRONTEND_IP }} "echo '✅ Frontend SSH Connected'"

    - name: Test SSH Connection (Backend)
      run: ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.BACKEND_IP }} "echo '✅ Backend SSH Connected'"

    - name: Update Configuration Files
      run: |
        sed -i "s/REPLACE_DOMAIN/${{ secrets.DOMAIN }}/g" ./configs/nginx.conf
        sed -i "s/REPLACE_DOMAIN/${{ secrets.DOMAIN }}/g" ./scripts/Frontend.sh
        sed -i "s/REPLACE_EMAIL/${{ secrets.EMAIL }}/g" ./scripts/Frontend.sh
        sed -i "s/BACKEND_IP/${{ secrets.BACKEND_IP }}/g" ./scripts/Frontend.sh
        sed -i "s/DB_USERNAME/${{ secrets.DB_USERNAME }}/g" ./scripts/Frontend.sh
        sed -i "s/DB_PASSWORD/${{ secrets.DB_PASSWORD }}/g" ./scripts/Frontend.sh
        sed -i "s/FRONTEND_IP/${{ secrets.FRONTEND_IP }}/g" ./scripts/Backend.sh
        sed -i "s/DB_USERNAME/${{ secrets.DB_USERNAME }}/g" ./scripts/Backend.sh
        sed -i "s/DB_PASSWORD/${{ secrets.DB_PASSWORD }}/g" ./scripts/Backend.sh

    - name: Upload Files to Frontend Server
      run: scp -i ~/.ssh/id_rsa -P ${{ secrets.SSH_PORT }} -r configs/ scripts/ ${{ secrets.SSH_USER }}@${{ secrets.FRONTEND_IP }}:~/chatbot_project/

    - name: Execute Frontend Deployment
      run: ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.FRONTEND_IP }} "bash ~/chatbot_project/scripts/Frontend.sh"

    - name: Upload Files to Backend Server
      run: scp -i ~/.ssh/id_rsa -P ${{ secrets.SSH_PORT }} -r scripts/ ${{ secrets.SSH_USER }}@${{ secrets.BACKEND_IP }}:~/chatbot_project/

    - name: Execute Backend Deployment
      run: ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.BACKEND_IP }} "bash ~/chatbot_project/scripts/Backend.sh"
